title: "Rohit Kandala"
name: "Rohit Kandala"
description: "Data Scientist Portfolio"
url: "https://rohitkandala.com"
baseurl: ""

include:
  - _pages

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

minimal_mistakes_skin: "sunrise"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: single

collections:
  projects:
    output: true
    permalink: /:collection/:name/
