title: "Rohit Kandala"
name: "Rohit Kandala"
description: "Data Scientist Portfolio"
url: "https://rohitkandala.com"
baseurl: ""

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: single

navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume
